# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
        cache: pip

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Linting with flake8
      run: |
        pip install flake8
        # find only changed *.py files compared to main
        CHANGED_FILES=$(git diff --name-only origin/main...HEAD -- '*.py')
        if [ -n "$CHANGED_FILES" ]; then
          echo "Running flake8 on changed files:"
          echo "$CHANGED_FILES"
          flake8 $CHANGED_FILES
        else
          echo "No Python files changed."
        fi
